const constants = {
   USERS_QUERY_LIMIT: 5,
   POSTS_QUERY_LIMIT: 5,
   SEARCH_POSTS_QUERY_LIMIT: 5,
   LAST_POSTS_QUERY_LIMIT: 4,
   DASHBOARD_POSTS_QUERY_LIMIT: 10,
   DASHBOARD_USERS_QUERY_LIMIT: 5,
};
export default constants;
